name: Build Cosmos Client
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.6'

      - name: Build
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
            ./gradlew build --stacktrace --no-daemon
          else
            gradle build --stacktrace --no-daemon
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: cosmos-client
          path: build/libs/*.jar
